2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Current SDK version is 0.18.5
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Configure stats pid to 21354
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Loading settings from /home/diejor/.config/wandb/settings
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Loading settings from /home/diejor/projects/aimf24/adCNN/src/wandb/settings
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'src/train.py', 'program_abspath': '/home/diejor/projects/aimf24/adCNN/src/train.py', 'program': 'train.py'}
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_init.py:_log_setup():534] Logging user logs to /home/diejor/projects/aimf24/adCNN/src/wandb/run-20241020_172555-9ma2ku4w/logs/debug.log
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_init.py:_log_setup():535] Logging internal logs to /home/diejor/projects/aimf24/adCNN/src/wandb/run-20241020_172555-9ma2ku4w/logs/debug-internal.log
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_init.py:init():621] calling init triggers
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_init.py:init():628] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'batch_size': 32, 'num_epochs': 20, 'focal_gamma': 2, 'scheduler_factor': 0.1, 'scheduler_patience': 2, 'optimizer': 'Adam', 'loss_function': 'FocalLoss', 'model': 'ResAD', 'git_commit': 'aabb7218ae13fad93de99ad90bf7a444ad6b9e60'}
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_init.py:init():671] starting backend
2024-10-20 17:25:55,130 INFO    MainThread:21354 [wandb_init.py:init():675] sending inform_init request
2024-10-20 17:25:55,134 INFO    MainThread:21354 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-20 17:25:55,134 INFO    MainThread:21354 [wandb_init.py:init():688] backend started and connected
2024-10-20 17:25:55,141 INFO    MainThread:21354 [wandb_init.py:init():783] updated telemetry
2024-10-20 17:25:55,154 INFO    MainThread:21354 [wandb_init.py:init():816] communicating run to backend with 90.0 second timeout
2024-10-20 17:25:55,406 ERROR   MainThread:21354 [wandb_init.py:init():842] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-20 17:25:55,406 ERROR   MainThread:21354 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/home/diejor/miniconda3/envs/adCNN/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/home/diejor/miniconda3/envs/adCNN/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 848, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-20 17:25:55,411 WARNING MsgRouterThr:21354 [router.py:message_loop():77] message_loop has been closed
